
### Some Explanation
This model is a rewritten adaptation of the Sharma et. al. Threat Net paper.
<p>Sharma S, Pannu J, Chorlton S, Swett JL, Ecker DJ. 
<br />Threat Net: A Metagenomic Surveillance Network for Biothreat Detection and Early Warning.
<br />Health Secur. 2023 Jun 27. doi: 10.1089/hs.2022.0160."))


SEIR System:
\begin{align*}

\frac{dS}{dt} &= - \underbrace{\beta S I / N}_\textrm{exposure to infection} 

\\

\frac{dE}{dt} &=  \underbrace{\beta S I / N}_\textrm{exposure to infection} - \underbrace{\sigma E}_\textrm{latency period}

\\

\frac{dI}{dt} &=  \underbrace{\sigma E}_\textrm{latency period} - \underbrace{\gamma I}_\text{recovery}

\\

\frac{dR}{dt} &= \underbrace{\gamma I}_\text{recovery}

\\
\end{align*}

Parameter Descriptions: <br />
$\beta$: effective contact rate <br />
$\sigma$: incubation time / rate at which exposed individuals become infectious  <br />
$\gamma$: rate at which infected individuals are removed (recover or die)  <br />
$R_0$: basic reproduction number 

Parameters per disease:

$$
\begin{array}{|c|c|c|c|c|c|c|}
\hline
& \textrm{SARS-CoV-2} & \textrm{Omicron BA.1} & \textrm{SARS}  & \textrm{MERS} & \begin{split}\textrm{Seasonal}\\ \textrm{Influenza}\end{split} & \textrm{1918 Pandemic} & \begin{split}\textrm{Avian}\\ \textrm{Influenza}\end{split} \\ \hline
\beta   & 0.32   & 1.19    & 0.24  & 0.11  & 0.33   & 0.5  & 0.12  \\ \hline
\sigma:  & 0.15   & 0.25 & 0.25  & 0.18   & 0.5   & 0.5   & 0.2   \\ \hline
\gamma:  & 0.125 & 0.125   & 0.1  & 0.13   & 0.25 & 0.25 & 0.11  \\ \hline
R_0:     & 2.5  & 9.5   & 2.4     & 0.9   & 1.3   & 2.0   & 1.1   \\ \hline
References  & (52–54)    & (53,55)  & (52,56) & (52,57–59) & (60)  & (52)  & (61,62) \\ \hline
\end{array}
$$
