---
title: "ThreatNet Israel"
author: "Meusel et al."
output:
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: minty # We can set color themes!
      #Also check out help on bs_themer
    vertical_layout: fill
    orientation: rows
    source_code: embed
# If we Output HTML, this allows Latex for the Documentation:  
# mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
runtime: shiny
---


```{r setup, include=FALSE}
library(tidyverse)
library(shiny)
library(flexdashboard)

source("Stochastic.r", local = TRUE)
load("results.RData")
```



Sidebar {.sidebar}
=====================================

### Inputs for Model

```{r}
actionButton(
  inputId = "run",
  label = "Run Simulations"
)
numericInput(
  inputId = "rep",
  label = "Simulation runs",
  value = 10
)
selectInput(
  inputId = "Disease_Scenario",
  label = "Disease Scenario",
  choices = Disease_names,
  selected = 1,
  multiple = FALSE
)
selectizeInput(
  inputId = "selected_hospitals",
  label = "Hospitals participating in Threatnet",
  choices = Hospital_visitors$Hospital,
  selected = Hospital_visitors$Hospital[1:6],
  multiple = TRUE,
  options = list(placeholder = "Select hospitals...")
)
actionButton("toggle_select", "Select/Deselect All")
sliderInput(
  inputId = "Threshold",
  label = "Detections needed to confirm disease",
  min = 1,
  max = 5,
  value = 1,
  step = 2,
  ticks = FALSE
)
sliderInput(
  inputId = "lag",
  label = "Average time between being infectious and (maybe) seeking care",
  min = 0,
  max = 7,
  value = 7,
  step = 3.5,
  ticks = FALSE
)
selectInput(
  inputId = "cases",
  label = "Y-axis of costs plot",
  choices = c("Cases at detection" = TRUE, "Time until detection" = FALSE),
  multiple = FALSE
)
```

Model Outputs
=======================================================================

Row
-----------------------------------------------------------------------

### Simulation runs until detection
The blue line is the theoretical deterministic outbreak progression, and the grey lines are stochastic realisations of possible outbreaks.
The red dots show when each outbreak is detected. This data is regenerated every time you press 'Run Simulations'.

```{r}
# set figure height
options(repr.plot.height = 5)
simulated_data <- eventReactive(input$run, {
  # Calculate average rate for the selected hospitals
  run_SEIR(
    disease_name = input$Disease_Scenario[[1]],
    rep = input$rep,
    threshold = input$Threshold,
    lag = input$lag,
    p = coverage(input$selected_hospitals) * delta * tau
  )
})

observeEvent(input$toggle_select, {
  # If any hospitals are selected, deselect all. Otherwise, select all.
  if (length(input$selected_hospitals) > 0) {
    new_selection <- character(0)  # Use an empty character vector to clear selections
  } else {
    new_selection <- Hospital_visitors$Hospital
  }
  updateSelectizeInput(session, "selected_hospitals", selected = new_selection)
})

renderPlot({
  data <- simulated_data()
  plot_SEIR(data)
}, height = 500)
```

### Costs of ThreatNet Israel
The blue line is the median outcome, and the grey area shows the 10th and 90th percentile of the outcomes.
The stochastic simulation was run 1000 times for each cost level.
This is pre-generated data and ignores the specific hospitals and number of replicates selected.
It still responds to the other parameters.

```{r}
subset_data <- reactive({
  results %>% 
    filter(d == input$Disease_Scenario, t == input$Threshold, output_cases == input$cases, lag == input$lag)
})

renderPlot({plot_cost(subset_data())}, height = 500)
```

Model Documentation
=======================================================================

Row
-----------------------------------------------------------------------
```{r test, child="Documentation.RMD", eval=TRUE, local=TRUE}
```
